
version: '2'

volumes:
  nginxdata: {}

services:
  web:
    image: nginx:latest
    mem_limit: 20000000
    logging:
      driver: awslogs
      options:
        awslogs-region: ${ECSO_AWS_REGION}
        awslogs-group: ${ECSO_CLUSTER_NAME}-hello-world
    ports:
      - "0:80"
    volumes:
      - nginxdata:/usr/share/nginx/html/:ro
    command: /bin/bash -c "echo \"server { location / { root /usr/share/nginx/html; try_files \$$uri /index.html =404; } }\" > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  backend:
    image: busybox:latest
    mem_limit: 10000000
    logging:
      driver: awslogs
      options:
        awslogs-region: ${ECSO_AWS_REGION}
        awslogs-group: ${ECSO_CLUSTER_NAME}-hello-world
    volumes:
      - nginxdata:/nginx
    command: sh -c "while true; do echo \"This is the hello-world service <p><pre>`env`</pre></p> \" > /nginx/index.html; sleep 3; done"
