Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    Cluster:
        Description: The name of the ECS cluster to deploy to
        Type: String

    AlertsTopic:
        Description: The ARN of the SNS topic to send alarm notifications to
        Type: String

    LoadBalancer:
        Description: The name of the load balancer
        Type: String

Resources:
    CPUUtilization:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmName: !Sub ${EnvironmentName}-alarm-cpu-utilisation
            AlarmDescription: CPU utilisation is high
            Namespace: AWS/ECS
            MetricName: CPUUtilization
            Statistic: Maximum
            Period: 60
            EvaluationPeriods: 2
            Threshold: 80
            ComparisonOperator: GreaterThanThreshold
            AlarmActions:
                - !Ref AlertsTopic
            Dimensions:
                - Name: ClusterName
                  Value: !Ref Cluster

    CPUReservation:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmName: !Sub ${EnvironmentName}-alarm-cpu-reservation
            AlarmDescription: Reserved CPU capcity is high
            Namespace: AWS/ECS
            MetricName: CPUReservation
            Statistic: Maximum
            Period: 60
            EvaluationPeriods: 2
            Threshold: 80
            ComparisonOperator: GreaterThanThreshold
            AlarmActions:
                - !Ref AlertsTopic
            Dimensions:
                - Name: ClusterName
                  Value: !Ref Cluster

    MemoryUtilization:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmName: !Sub ${EnvironmentName}-alarm-memory-utilisation
            AlarmDescription: Memory utilisation is high
            Namespace: AWS/ECS
            MetricName: MemoryUtilization
            Statistic: Maximum
            Period: 60
            EvaluationPeriods: 2
            Threshold: 80
            ComparisonOperator: GreaterThanThreshold
            AlarmActions:
                - !Ref AlertsTopic
            Dimensions:
                - Name: ClusterName
                  Value: !Ref Cluster

    MemoryReservation:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmName: !Sub ${EnvironmentName}-alarm-memory-reservation
            AlarmDescription: Reserved memory capcity is high
            Namespace: AWS/ECS
            MetricName: MemoryReservation
            Statistic: Maximum
            Period: 60
            EvaluationPeriods: 2
            Threshold: 80
            ComparisonOperator: GreaterThanThreshold
            AlarmActions:
                - !Ref AlertsTopic
            Dimensions:
                - Name: ClusterName
                  Value: !Ref Cluster
